### ISSUE TITLE
Support nested keys

### ISSUE THREAD

**Issue by 0X1A** [0X1A/yabs#11]
Embedding keys such as:

```
rules:
        clean:
                - rm -f $(BIN)
        install:
                - install -m $(BIN) $(DEST)
```

are currently not supported in the parser.
